{
 "title": "As Dashboard",
 "time": { "from": "2025-03-10T15:51:09.138Z", "to": "2025-03-11T03:51:09.138Z" },
 "panels": [
  {
   "title": "Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_client_request_duration_seconds_count{http_response_status_code=~\"4..\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(http_client_request_duration_seconds_count{http_response_status_code=~\"5..\"})",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(http_client_request_duration_seconds_count{http_response_status_code=~\"2..\"})",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "100 * rate(dotnet_process_cpu_time_seconds_total{cpu_mode=\"user\", instance=\"localhost:5045\", job=\"webApp\", otel_scope_name=\"System.Runtime\"}[1m]) / 6\n"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(http_server_request_duration_seconds_sum{http_request_method=\"GET\"}[5m]) \n  / \n  clamp_min(rate(http_server_request_duration_seconds_count{http_request_method=\"GET\"}[5m]), 1)\n)\n",
     "legendFormat": "Webapp (GET)"
    },
    {
     "expr": "sum(\n  rate(http_server_request_duration_seconds_sum{http_request_method=\"POST\"}[5m]) \n  / \n  clamp_min(rate(http_server_request_duration_seconds_count{http_request_method=\"POST\"}[5m]), 1)\n)\n",
     "legendFormat": "Webapp (POST)"
    }
   ]
  },
  {
   "title": "Items in Cart",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(eshop_AddToCart_item_total) by (item_id)"
    },
    {
     "expr": "sum(eshop_AddToCart_item_total)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}